import type { Metadata } from "next";
import "./globals.css";
import AppProviders from "@/providers/AppProviders";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <AppProviders>
        {children}
        </AppProviders>
      </body>
    </html>
  );
}
